x-postgres-credentials: &postgres-credentials
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: datesaver

services:
  postgres:
    image: postgres:15
    container_name: postgres_dapper_demo
    restart: always
    environment:
      <<: *postgres-credentials
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  demo:
    image: daywriter:latest
    restart: always
    ports:
      - "8080:80"
    build:
      context: DayWriter
      dockerfile: Dockerfile
      args:
        SOURCE_DIR: ${SOURCE_DIR}
    environment:
      <<: *postgres-credentials
      POSTGRES_CONNECTION_STRING: "Host=postgres;Port=5432;Database=datesaver;Username=postgres;Password=postgres"
    depends_on:
      - postgres

volumes:
  pgdata:
