apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daywriter.fullname" . }}
  labels:
    {{- include "daywriter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "daywriter.selectorLabels" . | nindent 6 }}

  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "daywriter.selectorLabels" . | nindent 8 }}
        {{- include "daywriter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - {{ .Values.env | quote }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ include "daywriter.name" . }}
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          env:
            - name: ENV
              value: {{ .Values.env | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.postgresql.passwordSecretKeyRefKey }}
                  name: {{ .Values.postgresql.passwordSecretKeyRefName }}
            - name: POSTGRES_CONNECTION_STRING
              value: "Host={{ .Release.Name }}-postgresql;Database={{ .Values.postgresql.database }};Port={{ .Values.postgresql.port }};Username={{ .Values.postgresql.username }};Password=$(POSTGRES_PASSWORD)"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ps aux | grep DayWriter | grep -v grep"
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelay | default 15 }}
            periodSeconds: {{ .Values.livenessProbe.period | default 20 }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ps aux | grep DayWriter | grep -v grep"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelay | default 5 }}
            periodSeconds: {{ .Values.readinessProbe.period | default 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: busybox:latest

          command:
            - sh
            - -c
            - |
              until nc -z {{ .Release.Name }}-postgresql {{ .Values.postgresql.port }}; do
                echo "Waiting for postgresql..."
                sleep 2
              done
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "daywriter.serviceAccountName" . }}
      tolerations:
        - effect: "NoSchedule"
          key: {{ .Values.env | quote }}
          operator: "Equal"
          value: "true"
        {{- with .Values.extraTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
