apiVersion: v1
kind: Service
metadata:
  name: {{ include "daywriter.fullname" . }}
  labels:
    {{- include "daywriter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "daywriter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  type: {{ .Values.service.type }}
